name: Release-please

# Give permissions to the release-please bot to open and update PRs
# and commit to PRs the repository to update Cargo.lock
permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  packages: write

# Run the workflow on push to the main branch and manually
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  publish-crates:
    name: Publish to crates.io
    runs-on: matterlabs-ci-runner-highdisk
    steps:
      - name: Publish crates
        uses: matter-labs/zksync-ci-common/.github/actions/publish-crates@aba-support-cargo-args
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_RELEASES }}
          cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
          run_build: 'true'
          cargo_build_args: '--workspace --exclude zksync_vm2_afl_fuzz'
          run_tests: 'false'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
